server:
  port: 8080
spring:
  application:
    name: szs
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:szs
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
springdoc:
  api-docs:
    path: /3o3/v3/api-docs
  swagger-ui:
    path: /3o3/swagger.html
    url: /3o3/v3/api-docs
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
  paths-to-match:
    - /szs/**
jwt:
  expiration: 3600000 # 1hour
#  expiration: 60000 # 1minute
  secret: c3pzLWp3dC10b2tlbi1zZWNyZXQta2V5LTIwMjUwMzE3 # szs-jwt-token-secret-key-20250317
encrypt:
  secret: szs-aes256secret
logging:
  level:
    org.springframework.web: debug
    org.hibernate.orm.jdbc.bind: trace
scrap-api:
  version: v1
  url: https://codetest-v4.3o3.co.kr/scrap
  key-field: X-API-KEY
  key: eUdJijcuJgmN/xtBKyK2bg==
refund:
  version: v1